apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-service
  # namespace: gam-test
spec:
  type: LoadBalancer
  ports:
    - port: 6000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hello-nginx
    owner: maplelabs

